server:
  port: 8000

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, busrefresh, info