server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingjaewon2000/spring-cloud-config
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info